name: Test Python Package

on:
  - push
  - pull_request

jobs:
  test:
    name: test with ${{ matrix.env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install tox
        run: uv tool install tox --with tox-uv --with tox-gh
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run test suite
        run: uv tool run --with tox-uv tox
