name: Test Python Package

on:
  - push
  - pull_request

jobs:
  test:
    name: test with python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Run test suite
        run: uv tool run --with tox-uv tox -e py
      - name: Run pre-commit
        if: matrix.python-version == '3.9'
        run: uv tool run --with tox-uv tox -e pre-commit
      - name: Test notebook
        if: matrix.python-version == '3.9'
        run: uv tool run --with tox-uv tox -e testnb

test:
    name: Run precommit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Run pre-commit
        run: uv tool run --with tox-uv tox -e pre-commit

test:
    name: Test notebook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Test notebook
        run: uv tool run --with tox-uv tox -e testnb
